import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  console.log("🌱 Seeding TinyThreads AI database...");

  // Create sellers
  const seller1 = await prisma.sellerProfile.upsert({
    where: { userId: "seed-seller-1" },
    update: {},
    create: {
      userId: "seed-seller-1",
      storeName: "HappyKidsCloset",
      storeDescription: "Mom of twins - selling clothes they've outgrown!",
      rating: 4.9,
      totalSales: 230,
      verified: true,
    },
  });

  const seller2 = await prisma.sellerProfile.upsert({
    where: { userId: "seed-seller-2" },
    update: {},
    create: {
      userId: "seed-seller-2",
      storeName: "LittleTrends",
      storeDescription: "Curated kids fashion at affordable prices",
      rating: 4.8,
      totalSales: 580,
      verified: true,
    },
  });

  // Create products
  const products = await Promise.all([
    prisma.product.create({
      data: {
        sellerId: seller1.id,
        title: "Dino Explorer Tee",
        description:
          "Roar-some cotton tee with colorful dinosaur prints. Super soft and tagless for sensitive skin. Perfect for little paleontologists!",
        price: 12.99,
        originalPrice: 22.99,
        size: "5T",
        brand: "Carter's",
        condition: "LIKE_NEW",
        category: "T_SHIRTS",
        status: "ACTIVE",
        gender: "unisex",
        season: "all-season",
        images: [],
        tags: ["dinosaur", "tee", "cotton", "sensory-friendly", "tagless"],
        color: "Green",
        aiTags: [
          "dinosaur",
          "tee",
          "affordable",
          "sensory-friendly",
          "popular",
        ],
        dealScore: 92,
        trendingScore: 87,
        resaleValue: 6.0,
        styleCategory: "casual",
        viewCount: 340,
        favoriteCount: 45,
      },
    }),
    prisma.product.create({
      data: {
        sellerId: seller2.id,
        title: "Space Adventure Set",
        description:
          "3-piece space-themed set: 1 rocket tee, 1 star shirt, 1 planet hoodie. All cotton, all awesome!",
        price: 24.99,
        originalPrice: 39.99,
        size: "5T",
        brand: "Primary",
        condition: "NEW",
        category: "OUTFITS",
        status: "ACTIVE",
        gender: "unisex",
        season: "all-season",
        images: [],
        tags: ["space", "astronaut", "rocket", "set", "bundle", "cotton"],
        color: "Blue",
        aiTags: ["space", "set", "bundle", "great_value", "popular"],
        dealScore: 88,
        trendingScore: 90,
        resaleValue: 12.0,
        styleCategory: "casual",
        viewCount: 275,
        favoriteCount: 38,
      },
    }),
    prisma.product.create({
      data: {
        sellerId: seller1.id,
        title: "Unicorn Dreams Hoodie",
        description:
          "Magical unicorn hoodie in soft blush pink. Fleece-lined for extra coziness. Gently used, still in excellent condition.",
        price: 15.0,
        originalPrice: 29.99,
        size: "4T",
        brand: "Old Navy",
        condition: "GOOD",
        category: "HOODIES",
        status: "ACTIVE",
        gender: "girl",
        season: "fall",
        images: [],
        tags: ["unicorn", "hoodie", "fleece", "pink", "cozy"],
        color: "Pink",
        aiTags: ["unicorn", "hoodie", "fall", "affordable", "cozy"],
        dealScore: 78,
        trendingScore: 65,
        resaleValue: 7.0,
        styleCategory: "casual",
        viewCount: 190,
        favoriteCount: 22,
      },
    }),
    prisma.product.create({
      data: {
        sellerId: seller2.id,
        title: "Sports Star T-Shirt",
        description:
          "Athletic tee for the little sports fan. Moisture-wicking fabric with baseball and basketball prints.",
        price: 9.99,
        originalPrice: 18.0,
        size: "S (7-8)",
        brand: "Nike",
        condition: "GOOD",
        category: "T_SHIRTS",
        status: "ACTIVE",
        gender: "boy",
        season: "all-season",
        images: [],
        tags: ["sports", "athletic", "tee", "nike", "moisture-wicking"],
        color: "Blue",
        aiTags: ["sports", "tee", "athletic", "brand_name", "popular"],
        dealScore: 72,
        trendingScore: 60,
        resaleValue: 5.0,
        styleCategory: "athletic",
        viewCount: 155,
        favoriteCount: 18,
      },
    }),
    prisma.product.create({
      data: {
        sellerId: seller1.id,
        title: "Rainbow Sparkle Dress",
        description:
          "Twirl-worthy dress with rainbow shimmer. Perfect for parties, photos, and everyday princess moments.",
        price: 18.5,
        originalPrice: 34.99,
        size: "3T",
        brand: "Cat & Jack",
        condition: "LIKE_NEW",
        category: "DRESSES",
        status: "ACTIVE",
        gender: "girl",
        season: "spring",
        images: [],
        tags: ["rainbow", "dress", "sparkle", "party", "princess"],
        color: "Rainbow",
        aiTags: ["rainbow", "dress", "party", "great_value", "spring"],
        dealScore: 85,
        trendingScore: 72,
        resaleValue: 9.0,
        styleCategory: "formal",
        viewCount: 210,
        favoriteCount: 31,
      },
    }),
    prisma.product.create({
      data: {
        sellerId: seller2.id,
        title: "Back to School Bundle",
        description:
          "5 shirts + 2 pants = 7 days of awesome school outfits. All 5T, all machine washable, mix and match.",
        price: 39.99,
        originalPrice: 65.0,
        size: "5T",
        brand: "Mixed Brands",
        condition: "LIKE_NEW",
        category: "BUNDLES",
        status: "ACTIVE",
        gender: "unisex",
        season: "fall",
        images: [],
        tags: ["school", "bundle", "outfits", "value", "mix-match"],
        color: "Mixed",
        aiTags: ["school", "bundle", "great_value", "fall", "essential"],
        dealScore: 95,
        trendingScore: 88,
        resaleValue: 20.0,
        styleCategory: "casual",
        viewCount: 420,
        favoriteCount: 65,
      },
    }),
    prisma.product.create({
      data: {
        sellerId: seller1.id,
        title: "Construction Crew Set",
        description:
          "Truck and digger themed top + cargo pants. Built tough for active toddlers who love construction sites.",
        price: 16.99,
        originalPrice: 28.0,
        size: "3T",
        brand: "Carter's",
        condition: "GOOD",
        category: "OUTFITS",
        status: "ACTIVE",
        gender: "boy",
        season: "all-season",
        images: [],
        tags: ["construction", "truck", "cargo", "set", "toddler"],
        color: "Yellow",
        aiTags: ["construction", "set", "toddler", "affordable", "boy"],
        dealScore: 75,
        trendingScore: 55,
        resaleValue: 8.0,
        styleCategory: "casual",
        viewCount: 130,
        favoriteCount: 12,
      },
    }),
    prisma.product.create({
      data: {
        sellerId: seller2.id,
        title: "Cozy Winter Pajama Set",
        description:
          "Fleece pajama 2-pack with non-slip feet. Kept our little one warm all winter!",
        price: 14.99,
        size: "2T",
        brand: "Hanna Andersson",
        condition: "GOOD",
        category: "PAJAMAS",
        status: "ACTIVE",
        gender: "unisex",
        season: "winter",
        images: [],
        tags: ["pajama", "fleece", "winter", "cozy", "set"],
        color: "Red",
        aiTags: ["pajama", "fleece", "winter", "cozy", "unicorn"],
        dealScore: 70,
        trendingScore: 40,
        resaleValue: 5.0,
        styleCategory: "casual",
        viewCount: 95,
        favoriteCount: 8,
      },
    }),
    prisma.product.create({
      data: {
        sellerId: seller1.id,
        title: "Summer Swim Trunks",
        description:
          "Quick-dry swim trunks with UV protection. Elastic waistband for easy changes at the pool.",
        price: 8.99,
        originalPrice: 19.99,
        size: "5T",
        brand: "Old Navy",
        condition: "LIKE_NEW",
        category: "SWIMWEAR",
        status: "ACTIVE",
        gender: "boy",
        season: "summer",
        images: [],
        tags: ["swim", "trunks", "UV", "summer", "quick-dry"],
        color: "Blue",
        aiTags: ["swim", "summer", "uv_protection", "affordable", "boy"],
        dealScore: 82,
        trendingScore: 45,
        resaleValue: 4.0,
        styleCategory: "athletic",
        viewCount: 78,
        favoriteCount: 6,
      },
    }),
    prisma.product.create({
      data: {
        sellerId: seller2.id,
        title: "Princess Castle Play Shirt",
        description:
          "Soft cotton shirt with cute castle and dragon print. Tagless for sensory comfort.",
        price: 7.5,
        originalPrice: 14.99,
        size: "4T",
        brand: "Cat & Jack",
        condition: "GOOD",
        category: "T_SHIRTS",
        status: "ACTIVE",
        gender: "girl",
        season: "all-season",
        images: [],
        tags: ["princess", "castle", "dragon", "shirt", "tagless"],
        color: "Purple",
        aiTags: [
          "princess",
          "castle",
          "affordable",
          "sensory-friendly",
          "girl",
        ],
        dealScore: 74,
        trendingScore: 50,
        resaleValue: 3.5,
        styleCategory: "casual",
        viewCount: 110,
        favoriteCount: 15,
      },
    }),
    prisma.product.create({
      data: {
        sellerId: seller1.id,
        title: "Organic Cotton Bodysuits (3-pack)",
        description:
          "GOTS-certified organic cotton bodysuits. Envelope neck for easy dressing. Minimal wear.",
        price: 19.99,
        originalPrice: 34.0,
        size: "2T",
        brand: "Burt's Bees Baby",
        condition: "LIKE_NEW",
        category: "ACCESSORIES",
        status: "ACTIVE",
        gender: "unisex",
        season: "all-season",
        images: [],
        tags: ["organic", "cotton", "bodysuit", "newborn", "eco-friendly"],
        color: "White",
        aiTags: ["organic", "cotton", "eco-friendly", "value", "essential"],
        dealScore: 86,
        trendingScore: 70,
        resaleValue: 10.0,
        styleCategory: "casual",
        viewCount: 200,
        favoriteCount: 28,
      },
    }),
    prisma.product.create({
      data: {
        sellerId: seller2.id,
        title: "Lightning Running Shoes",
        description:
          "Light-up sneakers size 10T. Velcro straps - no laces to trip over! Lights still work perfectly.",
        price: 22.0,
        originalPrice: 39.99,
        size: "XS (5-6)",
        brand: "Stride Rite",
        condition: "GOOD",
        category: "SHOES",
        status: "ACTIVE",
        gender: "unisex",
        season: "all-season",
        images: [],
        tags: ["shoes", "sneakers", "light-up", "velcro", "comfortable"],
        color: "Blue",
        aiTags: ["shoes", "sneakers", "light-up", "velcro", "affordable"],
        dealScore: 68,
        trendingScore: 55,
        resaleValue: 8.0,
        styleCategory: "athletic",
        viewCount: 165,
        favoriteCount: 20,
      },
    }),
    prisma.product.create({
      data: {
        sellerId: seller1.id,
        title: "Holiday Plaid Dress",
        description:
          "Festive plaid dress worn once for holiday photos. In perfect condition with matching hair bow!",
        price: 16.5,
        originalPrice: 32.0,
        size: "4T",
        brand: "Hanna Andersson",
        condition: "LIKE_NEW",
        category: "DRESSES",
        status: "ACTIVE",
        gender: "girl",
        season: "winter",
        images: [],
        tags: ["holiday", "plaid", "dress", "festive", "like-new"],
        color: "Red",
        aiTags: ["holiday", "dress", "like_new", "winter", "value"],
        dealScore: 80,
        trendingScore: 35,
        resaleValue: 8.0,
        styleCategory: "formal",
        viewCount: 88,
        favoriteCount: 10,
      },
    }),
    prisma.product.create({
      data: {
        sellerId: seller2.id,
        title: "Denim Overalls",
        description:
          "Classic denim overalls with adjustable straps. Room to grow! Cute embroidered animals on the front pocket.",
        price: 13.99,
        size: "3T",
        brand: "OshKosh B'gosh",
        condition: "GOOD",
        category: "PANTS",
        status: "ACTIVE",
        gender: "unisex",
        season: "all-season",
        images: [],
        tags: ["denim", "overalls", "durable", "adjustable", "toddler"],
        color: "Blue",
        aiTags: ["denim", "overalls", "durable", "adjustable", "toddler"],
        dealScore: 65,
        trendingScore: 40,
        resaleValue: 6.0,
        styleCategory: "casual",
        viewCount: 72,
        favoriteCount: 7,
      },
    }),
    prisma.product.create({
      data: {
        sellerId: seller1.id,
        title: "Spring Floral Romper",
        description:
          "Adorable floral romper perfect for spring photos and Easter. Snap buttons for easy diaper changes.",
        price: 11.99,
        originalPrice: 24.0,
        size: "2T",
        brand: "Cat & Jack",
        condition: "LIKE_NEW",
        category: "OUTFITS",
        status: "ACTIVE",
        gender: "girl",
        season: "spring",
        images: [],
        tags: ["floral", "romper", "spring", "snap-buttons", "toddler"],
        color: "Pink",
        aiTags: ["floral", "romper", "spring", "like_new", "girl"],
        dealScore: 76,
        trendingScore: 48,
        resaleValue: 5.5,
        styleCategory: "casual",
        viewCount: 95,
        favoriteCount: 13,
      },
    }),
  ]);

  // Create an auction for the dinosaur tee
  await prisma.auction.create({
    data: {
      productId: products[0].id,
      sellerId: seller1.id,
      startPrice: 5.0,
      currentPrice: 8.5,
      buyNowPrice: 12.99,
      bidIncrement: 1.0,
      startTime: new Date(),
      endTime: new Date(Date.now() + 60 * 60 * 1000), // 1 hour from now
      status: "LIVE",
      auctionType: "standard",
      bidCount: 4,
      watcherCount: 12,
    },
  });

  console.log(`✅ Seeded ${products.length} products, 2 sellers, 1 auction`);
  console.log("🎉 Database seeded successfully!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
